---
# This block defines the storage volume for the jupyter notebook
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pv-claim
  labels:
    app: jupyter
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

# This block defines a Pod for the Docker Private Registry
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
      containers:
        - name: jupyter
          image: docker-registry:32500/jupyter/jupyter:v0.1.0
          volumeMounts:
            - name: jupyter-persistent
              mountPath: /notebooks
          env:
            - name: JUPYTER_PORT
              value: "8888"

      imagePullSecrets:
        - name: reg-user-secret
      volumes:
        - name: jupyter-persistent
          persistentVolumeClaim:
            claimName: jupyter-pv-claim

---
# This block defines the service access to the registry pod
apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  selector:
    app: jupyter
  ports:
    - name: http
      nodePort: 32288
      port: 8888
  type: NodePort
---
