apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw
  template:
    metadata:
      labels:
        app: excalidraw
    spec:
      containers:
        - name: excalidraw
          image: docker-registry:32500/excalidraw/excalidraw:v0.17.5-1
      imagePullSecrets:
        - name: reg-user-secret

---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw
spec:
  selector:
    app: excalidraw
  ports:
    - name: http
      nodePort: 32300
      port: 80
  type: NodePort
